version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_ping_bot
    restart: always
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - SESSION_NAME=${SESSION_NAME:-bot_session}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - PHRASES_FILE=${PHRASES_FILE:-data/phrases.json}
      - DEAD_CHAT_MINUTES=${DEAD_CHAT_MINUTES:-15}
      - KILL_RANDOM_MUTE_HOURS=${KILL_RANDOM_MUTE_HOURS:-1}
      - STORAGE_PATH=${STORAGE_PATH:-/app/storage}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./storage:/app/storage
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
